### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by EvergreenSystems** [GizmoTheMoonPig/Subtitle-Blocker#1]
The mod causes a crash upon startup, the mod pack is otherwise stable.

Forge: 39.0.59
Mod version: 1.0

Crash log: https://gist.github.com/Shedao-Shai/7a1472f34568b6e35da06d5e71de905c
Debug log: https://gist.github.com/Shedao-Shai/0bc170880d0e5f384ed63c88aea2dc03
Latest log: https://gist.github.com/Shedao-Shai/8d55d92c0de43d6be758b8cda55274af

**Comment by GizmoTheMoonPig** [comment]
fixed in d1a7dd24104f2b98cab0bf7e07a40b6f0782f645, not sure why this didn't happen to me. New build will be available on Curseforge soon (I hope). Thanks for the report!
